apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserver.edt.org
  labels:
    app: kserver.edt.org
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kserver.edt.org
  template:
    metadata:
      labels:
        app: kserver.edt.org
    spec:
      containers:
      - name: kserver
        image: robert72004/kserver:minikube
        imagePullPolicy: Always
