apiVersion: v1
kind: Service
metadata:
  name: kserver
  labels:
    app: kserver
spec:
  type: NodePort
  ports:
  - port: 88
    targetPort: 88
    nodePort: 88
    protocol: TCP
    name: kserver0
  - port: 464
    targetPort: 464
    nodePort: 464
    protocol: TCP
    name: kserver1
  - port: 749
    targetPort: 749
    nodePort: 749
    protocol: TCP
    name: kserver2
  selector:
    app: kserver.edt.org
