apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: lap
spec:
  type: NodePort
  ports:
  - port: 389
    targetPort: 389
    nodePort: 389
    protocol: TCP
    name: ldap
  selector:
    app: ldap  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: robert72004/ldapserver:minikube
        imagePullPolicy: Always
