apiVersion: v1
kind: Service
metadata:
  name: samba-homes
  labels:
    app: samba-homes
spec:
  type: NodePort
  ports:
  - port: 445
    targetPort: 445
    nodePort: 445
    protocol: TCP
    name: samba-homes0
  - port: 139
    targetPort: 139
    nodePort: 139
    protocol: TCP
    name: samba-homes1
  selector:
    app: samba-homes
